# Generated by Django 3.2.5 on 2021-09-21 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedrijf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=124, unique=True)),
                ('holding', models.CharField(blank=True, max_length=124, null=True)),
                ('sector', models.CharField(blank=True, max_length=124, null=True)),
                ('belangenvereniging', models.CharField(blank=True, max_length=124, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=124)),
                ('omschrijving', models.CharField(blank=True, max_length=124, null=True)),
                ('randvoorwaarden', models.CharField(blank=True, max_length=124, null=True)),
                ('afhankelijkheid_doorgaan', models.CharField(blank=True, max_length=124, null=True)),
                ('benodigde_innovatie', models.CharField(blank=True, max_length=124, null=True)),
                ('mogelijke_versnelling', models.CharField(blank=True, max_length=124, null=True)),
                ('aanspraak_subsidie', models.CharField(blank=True, max_length=124, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=124)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adres', models.CharField(blank=True, max_length=124, null=True)),
                ('postcode', models.CharField(blank=True, max_length=124, null=True)),
                ('woonplaats', models.CharField(blank=True, max_length=124, null=True)),
                ('productiegroei_2020_2025', models.FloatField(blank=True, default=0, null=True)),
                ('productiegroei_2020_2030', models.FloatField(blank=True, default=0, null=True)),
                ('wkk', models.BooleanField(default=False)),
                ('wkk_2030', models.BooleanField(default=False)),
                ('bedrijf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestiging_naam', to='plants.bedrijf')),
            ],
            options={
                'unique_together': {('naam', 'lattitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Project_kerngetallen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aardgas_verandering', models.FloatField(default=0)),
                ('biogas_verandering', models.FloatField(default=0)),
                ('elektriciteit_verandering', models.FloatField(default=0)),
                ('verzwaring_netaansluiting', models.FloatField(default=0)),
                ('stoom_verandering', models.FloatField(default=0)),
                ('overige_warmte_verandering', models.FloatField(default=0)),
                ('biomassa_verandering', models.FloatField(default=0)),
                ('afval_verandering', models.FloatField(default=0)),
                ('waterstof_energie_verandering', models.FloatField(default=0)),
                ('productie_verandering', models.FloatField(default=0)),
                ('co2_uitstoot_verandering', models.FloatField(default=0)),
                ('nox_uitstoot_verandering', models.FloatField(default=0)),
                ('jaar_realisatie', models.IntegerField()),
                ('status', models.CharField(choices=[('zeker', 'Zeker'), ('voorw', 'Voorwaardelijk'), ('onzeker', 'Onzeker')], default='onzeker', max_length=8)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='vestiging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestiging_project', to='plants.vestiging'),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('lattitude', models.FloatField(blank=True, null=True)),
                ('longtitude', models.FloatField(blank=True, null=True)),
                ('vestiging', models.CharField(blank=True, max_length=124, null=True)),
                ('plaats', models.CharField(blank=True, max_length=124, null=True)),
                ('sector', models.CharField(blank=True, max_length=124, null=True)),
                ('branchevereniging', models.CharField(blank=True, max_length=124, null=True)),
            ],
            options={
                'unique_together': {('name', 'lattitude', 'longtitude')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('vestiging', 'naam')},
        ),
        migrations.CreateModel(
            name='Energie_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('aardgas', models.FloatField(default=0)),
                ('biogas', models.FloatField(default=0)),
                ('elektriciteit', models.FloatField(default=0)),
                ('stoom', models.FloatField(default=0)),
                ('overige_warmte', models.FloatField(default=0)),
                ('biomassa', models.FloatField(default=0)),
                ('afval', models.FloatField(default=0)),
                ('waterstof', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
                ('vestiging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestiging_energieimport', to='plants.vestiging')),
            ],
            options={
                'unique_together': {('vestiging', 'jaar')},
            },
        ),
        migrations.CreateModel(
            name='Energie_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField()),
                ('aardgas', models.FloatField(default=0)),
                ('biogas', models.FloatField(default=0)),
                ('elektriciteit', models.FloatField(default=0)),
                ('stoom', models.FloatField(default=0)),
                ('overige_warmte', models.FloatField(default=0)),
                ('biomassa', models.FloatField(default=0)),
                ('afval', models.FloatField(default=0)),
                ('waterstof', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
                ('vestiging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestiging_energieexport', to='plants.vestiging')),
            ],
            options={
                'unique_together': {('vestiging', 'jaar')},
            },
        ),
    ]
