# Generated by Django 3.2.5 on 2021-10-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vestiging',
            old_name='naam',
            new_name='vestigingnaam',
        ),
        migrations.AlterUniqueTogether(
            name='vestiging',
            unique_together={('vestigingnaam', 'lattitude', 'longitude')},
        ),
    ]
