# Generated by Django 3.2.5 on 2023-07-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20211005_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
